In [15]:
import pandas as pd
import numpy as np
import json
import requests
import statsmodels.api as sm

In [9]:
headers = {
    'Accept': '*/*',
    'Accept-Language': 'en-US,en;q=0.9',
    'Connection': 'keep-alive',
    'Origin': 'https://www.nba.com',
    'Referer': 'https://www.nba.com/',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
    'sec-ch-ua': '"Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"macOS"',
    'Host': 'stats.nba.com',
    'x-nba-stats-origin': 'stats',
    'x-nba-stats-token': 'true'
}
def json_extract():
    years = ['2023-24', '2022-23', '2021-22','2019-20','2018-19']
    all_data = []  # List to store data from all years

    for year in years:
        url = F'https://stats.nba.com/stats/leaguedashteamstats?Conference=&DateFrom=&DateTo=&Division=&GameScope=&GameSegment=&Height=&ISTRound=&LastNGames=0&LeagueID=00&Location=&MeasureType=Four%20Factors&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode=PerGame&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season={year}&SeasonSegment=&SeasonType=Regular%20Season&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision='

        try:
            response = requests.get(url, headers=headers)
            if response.status_code == 200:
                data = response.json()
                print(f"Successfully got data for {year}!")
                
                # Create DataFrame for current year
                df_year = pd.DataFrame(data['resultSets'][0]['rowSet'], 
                                     columns=data['resultSets'][0]['headers'])
                
                # Add year column
                df_year['Season'] = year
                
                # Append to list of DataFrames
                all_data.append(df_year)
            else:
                print(f"Failed to get data for {year}: Status code {response.status_code}")
                
        except Exception as e:
            print(f"Error occurred for {year}: {e}")

    # Combine all DataFrames
    final_df = pd.concat(all_data, ignore_index=True)
    return final_df

# Execute function and store result
combined_df = json_extract()
combined_df.head()

Successfully got data for 2023-24!
Successfully got data for 2022-23!
Successfully got data for 2021-22!
Successfully got data for 2019-20!
Successfully got data for 2018-19!

,TEAM_ID,TEAM_NAME,GP,W,L,W_PCT,MIN,EFG_PCT,FTA_RATE,TM_TOV_PCT,...,MIN_RANK,EFG_PCT_RANK,FTA_RATE_RANK,TM_TOV_PCT_RANK,OREB_PCT_RANK,OPP_EFG_PCT_RANK,OPP_FTA_RATE_RANK,OPP_TOV_PCT_RANK,OPP_OREB_PCT_RANK,Season
0,1610612737,Atlanta Hawks,82,36,46,0.439,3971.0,0.539,0.251,0.133,...,3,17,12,13,5,30,16,11,16,2023-24
1,1610612738,Boston Celtics,82,64,18,0.780,3966.0,0.578,0.224,0.121,...,7,2,25,1,14,2,1,29,7,2023-24
2,1610612751,Brooklyn Nets,82,32,50,0.390,3961.0,0.531,0.234,0.134,...,10,25,20,14,12,16,14,24,19,2023-24
3,1610612766,Charlotte Hornets,82,21,61,0.256,3946.0,0.529,0.212,0.140,...,23,26,30,21,27,29,11,10,22,2023-24
4,1610612741,Chicago Bulls,82,39,43,0.476,3996.0,0.534,0.236,0.124,...,1,22,19,3,11,23,19,8,17,2023-24

In [10]:
combined_df.head(100)

,TEAM_ID,TEAM_NAME,GP,W,L,W_PCT,MIN,EFG_PCT,FTA_RATE,TM_TOV_PCT,...,MIN_RANK,EFG_PCT_RANK,FTA_RATE_RANK,TM_TOV_PCT_RANK,OREB_PCT_RANK,OPP_EFG_PCT_RANK,OPP_FTA_RATE_RANK,OPP_TOV_PCT_RANK,OPP_OREB_PCT_RANK,Season
0,1610612737,Atlanta Hawks,82,36,46,0.439,3971.0,0.539,0.251,0.133,...,3,17,12,13,5,30,16,11,16,2023-24
1,1610612738,Boston Celtics,82,64,18,0.780,3966.0,0.578,0.224,0.121,...,7,2,25,1,14,2,1,29,7,2023-24
2,1610612751,Brooklyn Nets,82,32,50,0.390,3961.0,0.531,0.234,0.134,...,10,25,20,14,12,16,14,24,19,2023-24
3,1610612766,Charlotte Hornets,82,21,61,0.256,3946.0,0.529,0.212,0.140,...,23,26,30,21,27,29,11,10,22,2023-24
4,1610612741,Chicago Bulls,82,39,43,0.476,3996.0,0.534,0.236,0.124,...,1,22,19,3,11,23,19,8,17,2023-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1610612739,Cleveland Cavaliers,65,19,46,0.292,3145.0,0.522,0.227,0.165,...,27,22,29,30,2,30,2,25,9,2019-20
96,1610612742,Dallas Mavericks,75,43,32,0.573,3635.0,0.545,0.264,0.126,...,1,4,12,3,12,13,6,30,8,2019-20
97,1610612743,Denver Nuggets,73,46,27,0.630,3549.0,0.535,0.235,0.139,...,3,10,26,9,3,17,14,14,20,2019-20
98,1610612765,Detroit Pistons,66,20,46,0.303,3193.0,0.529,0.261,0.155,...,24,19,17,27,11,22,7,18,25,2019-20
99,1610612744,Golden State Warriors,65,15,50,0.231,3145.0,0.497,0.264,0.146,...,27,30,14,19,25,28,11,6,21,2019-20

In [12]:
#Let's run our data and get a statistical summary. First we have to create a new column and do some math into the new column
def calc_dev():
    combined_df['Shooting Dev'] = combined_df['EFG_PCT']-combined_df['OPP_EFG_PCT']
    combined_df['Rebounding Dev'] = combined_df['OREB_PCT']-combined_df['OPP_OREB_PCT']
    combined_df['Turnover Dev'] = combined_df['TM_TOV_PCT']-combined_df['OPP_TOV_PCT']
    combined_df['Free Throw Dev'] = combined_df['FTA_RATE']-combined_df['OPP_FTA_RATE']
    return combined_df
calc_dev()
combined_df.head(5)

,TEAM_ID,TEAM_NAME,GP,W,L,W_PCT,MIN,EFG_PCT,FTA_RATE,TM_TOV_PCT,...,OREB_PCT_RANK,OPP_EFG_PCT_RANK,OPP_FTA_RATE_RANK,OPP_TOV_PCT_RANK,OPP_OREB_PCT_RANK,Season,Shooting Dev,Rebounding Dev,Turnover Dev,Free Throw Dev
0,1610612737,Atlanta Hawks,82,36,46,0.439,3971.0,0.539,0.251,0.133,...,5,30,16,11,16,2023-24,-0.033,0.025,-0.006,0.009
1,1610612738,Boston Celtics,82,64,18,0.780,3966.0,0.578,0.224,0.121,...,14,2,1,29,7,2023-24,0.055,0.013,-0.001,0.035
2,1610612751,Brooklyn Nets,82,32,50,0.390,3961.0,0.531,0.234,0.134,...,12,16,14,24,19,2023-24,-0.012,0.004,0.005,-0.005
3,1610612766,Charlotte Hornets,82,21,61,0.256,3946.0,0.529,0.212,0.140,...,27,29,11,10,22,2023-24,-0.043,-0.038,0.001,-0.024
4,1610612741,Chicago Bulls,82,39,43,0.476,3996.0,0.534,0.236,0.124,...,11,23,19,8,17,2023-24,-0.022,0.008,-0.018,-0.015

In [16]:
#Let's prepare our data for the regression model
X = combined_df[['Shooting Dev', 'Rebounding Dev', 'Turnover Dev', 'Free Throw Dev']]
y = combined_df['W_PCT']

# Add a constant to the independent value
X = sm.add_constant(X)

#Fit the Model
model = sm.OLS(y, X).fit()

#Get summary of the model
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  W_PCT   R-squared:                       0.917
Model:                            OLS   Adj. R-squared:                  0.915
Method:                 Least Squares   F-statistic:                     402.6
Date:                Wed, 22 Jan 2025   Prob (F-statistic):           2.04e-77
Time:                        01:28:09   Log-Likelihood:                 265.07
No. Observations:                 150   AIC:                            -520.1
Df Residuals:                     145   BIC:                            -505.1
Df Model:                           4
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
const              0.5006      0.003    145.819      0.000       0.494       0.507
Shooting Dev       4.6282      0.134     34.659      0.000       4.364       4.892
Rebounding Dev     1.5397      0.133     11.602      0.000       1.277       1.802
Turnover Dev      -3.7446      0.246    -15.251      0.000      -4.230      -3.259
Free Throw Dev     0.6154      0.125      4.939      0.000       0.369       0.862
==============================================================================
Omnibus:                        3.280   Durbin-Watson:                   1.902
Prob(Omnibus):                  0.194   Jarque-Bera (JB):                2.206
Skew:                          -0.090   Prob(JB):                        0.332
Kurtosis:                       2.434   Cond. No.                         72.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [35]:
#Let's create a function that will allow us to easily extract shooting dev, rebounding dev, turnover dev, and free throw dev for a team and year
def get_team_stats(team, year):
    team_data = combined_df[(combined_df['TEAM_NAME'] == team) & (combined_df['Season'] == year)]
    shooting_dev = team_data['Shooting Dev'].values[0]
    rebounding_dev = team_data['Rebounding Dev'].values[0]
    turnover_dev = team_data['Turnover Dev'].values[0]
    free_throw_dev = team_data['Free Throw Dev'].values[0]
    wins = int(team_data['W'].values[0])
    
    predicted_win_pct = ( 
        model.params['const']+ 
        (shooting_dev * model.params['Shooting Dev']) +
        (rebounding_dev * model.params['Rebounding Dev']) +
        (turnover_dev * model.params['Turnover Dev']) +
        (free_throw_dev * model.params['Free Throw Dev']))
    
    predicted_wins = round(predicted_win_pct * 82)

    return {
        'Predicted Wins': predicted_wins,
        'Actual Wins': wins
    }

#Let's test our function
get_team_stats('Denver Nuggets', '2021-22')

{'Predicted Wins': 45, 'Actual Wins': 48}